// src/keyMappings.js
const keyMappings = {
    originType: "Origin Type",
    hostname: "Hostname",
    forwardHostHeader: "Forward Host Header",
    cacheKeyHostname: "Cache Key Hostname",
    compress: "Supports Compression",
    enableTrueClientIp: "Enable True Client IP",
    trueClientIpHeader: "True Client IP Header",
    trueClientIpClientSetting: "Client IP Client Setting",
    originCertificate: "Origin Certificate",
    verificationMode: "Verification Mode",
    originSni: "Use Origin SNI",
    ports: "Ports",
    httpPort: "HTTP Port",
    httpsPort: "HTTPS Port",
    customValidCnValues: "Custom Valid CN Values",
    originCertsToHonor: "Origin Certificates to Honor",
    standardCertificateAuthorities: "Standard Certificate Authorities",
    responseCode: "Response Code",
    queryString: "Query String",
    mobileDefaultChoice: "Mobile Default Choice",
    action: "Action",
    customHeaderName: "Custom Header Name",
    newHeaderValue: "New Header Value",
    avoidDuplicateHeaders: "Avoid Duplicate Headers",
    values: "Values",
    matchOperator: "Match Operator",
    enabled: "Enabled",
    behavior: "Behavior",
    ttl: "Time-to-Live",
    mustRevalidate: "Must Revalidate",
    delay: "Delay",
    timeout: "Timeout",
    logHost: "Log Host",
    logReferer: "Log Referer",
    logUserAgent: "Log User Agent",
    logAcceptLanguage: "Log Accept Language",
    logCookies: "Log Cookies",
    logCustomLogField: "Log Custom Field",
    retryCount: "Retry Count",
    retryInterval: "Retry Interval",
    maximumReconnects: "Maximum Reconnects"
  };
  
  export default keyMappings;
  